### ISSUE TITLE
Container job with cloud bucket mount is failing with error: mkdir: cannot create directory '/mnt/share': Read-only file system

### ISSUE THREAD

**Issue by seandavi** [GoogleCloudPlatform/batch-samples#21]
Starting sometime today, I am getting the error noted in the title when running container jobs (transcoding) with a GCS mount. Simple script jobs work as expected. The same job descriptions were working without errors yesterday. I'm running in us-central1. 

For transparency, I have asked for assistance on the Google Cloud Forums as well:

https://www.googlecloudcommunity.com/gc/Infrastructure-Compute-Storage/Seeing-new-error-mounting-GCS-bucket-on-Google-Cloud-Batch/td-p/470236

**Comment by seandavi** [comment]
I tried another batch job, but mounting at `/mnt/disks/MY_BUCKET` and was successful. This seems to make sense based on: https://cloud.google.com/container-optimized-os/docs/concepts/disks-and-filesystem#working_with_the_file_system
So the example here might need to be updated? Not sure if this is a permanent change with Batch or just something I'm noticing right now.

**Comment by aaronegolden** [comment]
You are correct @seandavi. COS doesn't allow creating the mount path directly under /mnt like we were doing in some of the original samples. Strictly speaking /mnt/share should still be fine for jobs that use the batch-debian boot image, or anything else not COS, but nowadays we try to use /mnt/**disks**/foo everywhere, just to avoid that potential stumbling block in case of switching to COS.
